#!/bin/bash

export PYTHONPATH=.

s=0
gpu=1
# py_script="python run/train.py -a happo_mb happo_mb dynamics -e ma_mujoco-Ant_2x4 -c ma_mujoco -ld debug-logs -n debug -s $s --gpu $gpu -ki 2"
# py_script="python run/train.py -a happo -e smac-5m_vs_6m -c smac -ld debug-logs -n debug2 -s 4" # -kw 0#dynamics_name=dynamics 0#n_epochs=100 1#n_epochs=5"
# py_script="python run/train.py -a happo_mb sdynamics -e smac-5m_vs_6m -c smac -ld debug-logs -n debug2 -s 4 -te train_smac"
# py_script="python run/train.py -a happo -e grf-11_vs_11_hard_stochastic -c grf -ld debug-logs -n debug2 -s 4"
py_script="python run/train.py -a happo -e grf-academy_3_vs_1_with_keeper -c academy_3_vs_1_with_keeper -ld debug-logs -n debug2 -s 4"
# py_script="python run/train.py -a masac_lka dynamics -e ma_mujoco-Walker2d_2x3 -c ma_mujoco -ld ma_mujoco-logs -n new_buffer -s 3 --gpu 3 -kw 0#dynamics_name=dynamics 0#n_epochs=1000 0#n_lka_epochs=100 0#n_simulated_envs=100 1#ergodic=True 1#n_epochs=5 1#model_loss_type=mbpo"
echo $py_script
eval $py_script
echo "Script completed"
