#!/bin/bash

export PYTHONPATH=.

s=0
gpu=1
# py_script="python run/train.py -a happo_mb happo_mb dynamics -e ma_mujoco-Ant_2x4 -c ma_mujoco -ld debug-logs -n debug -s $s --gpu $gpu -ki 2"
py_script="python run/train.py -a mambpo dynamics -e ma_mujoco-Ant_2x4 -c -ld debug-logs -n debug -s 4 -kw 0#dynamics_name=dynamics 0#n_epochs=100 0#n_simulated_envs=100 1#ergodic=True 1#n_epochs=1"
echo $py_script
eval $py_script
echo "Script completed"