#!/bin/bash

# brew install ffmpeg
export PYTHONPATH=.

algos=(zero)
suite=magw
# envs=(escalation staghunt harvest)
envs=(escalation)
config=magw
args1=(0 1)
args2=(64)
args3=(5e-4)
date=$(date +"%m%d")
info=""
ld="${suite}-logs"
gpus=$(nvidia-smi -L | wc -l)
# for x in $(seq 1 1); do
#     shift
# done

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

for e in "${envs[@]}"; do
    for a in "${algos[@]}"; do
        # for a1 in "${args1[@]}"; do
        for s in {1..10}; do
            la1=${#args1[@]}
            idx=$(($INF_MAC_NODE_RANK % $la1))
            a1=${args1[$idx]}
            la2=${#args2[@]}
            idx=$(($INF_MAC_NODE_RANK % $la2))
            a2=${args2[$idx]}
            kws="n_imaginary_runs=$a1 n_envs=$a2"
            # echo $kws
            env="${suite}-${e}"
            if [[ "$OSTYPE" == 'linux-gnu'* ]]; then
                gpu=$(($i % $gpus))
                py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -s $s --gpu $gpu -na 2 -kw $kws &"
            else
                py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -s $s -na 2 -kw $kws &"
            fi
            echo $py_script
            eval $py_script
            ((i=(i+1) ))
        done
        # done
        # wait
    done
    wait
done
wait
echo "Script completed"
