#!/bin/bash

export PYTHONPATH=.

# algos=(happo)
algos=(happo_lka)
suite=mpe
envs=(simple_tag)
config=simple_tag
na=3
args1=(2)
args2=(1 3 5)
date=$(date +"%m%d")
info=""
ld="${suite}-logs"
gpus=$(nvidia-smi -L | wc -l)

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

# ========== scripts for happo ===========

# i=0
# INF_MAC_NODE_RANK=0
# for e in "${envs[@]}"; do
#     config="${config}"
#     for a in "${algos[@]}"; do
#         for a1 in "${args1[@]}"; do
#             for s in {0..4}; do
#                 kws="num_landmarks=$a1"
#                 env="${suite}-${e}"
#                 if [[ "$OSTYPE" == 'linux-gnu'* ]]; then
#                     gpu=$(($i % $gpus))
#                     py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -s $s --gpu $gpu -na $na -kw $kws &"
#                 else
#                     py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -s $s -na $na -kw $kws &"
#                 fi
#                 echo $py_script
#                 eval $py_script
#                 ((i=(i+1) ))
#             done
#         done
#     done
# done
# wait
# echo "Script completed"

# ========== scripts for happo_lka ===========

i=0
INF_MAC_NODE_RANK=0
for e in "${envs[@]}"; do
    config="${config}"
    for a in "${algos[@]}"; do
        for a1 in "${args1[@]}"; do
            for a2 in "${args2[@]}"; do
                for s in {0..4}; do
                    kws="num_landmarks=$a1 n_imaginary_runs=$a2"
                    env="${suite}-${e}"
                    if [[ "$OSTYPE" == 'linux-gnu'* ]]; then
                        gpu=$(($i % $gpus))
                        py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -s $s --gpu $gpu -na $na -kw $kws &"
                    else
                        py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -s $s -na $na -kw $kws &"
                    fi
                    echo $py_script
                    eval $py_script
                    ((i=(i+1) ))
                done
            done
        done
    done
done
wait
echo "Script completed"