#!/bin/bash

export PYTHONPATH=.

# algos=(zero)
algos=(lka_v2)
# suite=ma_mujoco
# suite=magw
suite=ma_minigrid
# envs=(escalation staghunt harvest)
# envs=(HalfCheetah_3x2)
# envs=(escalation)
envs=(treasure)
# envs=(Ant_4x2)
# envs=(Hopper)
# config=escalation
config=ma_minigrid
na=2
# args1=(0 1 3)
args1=(3)
date=$(date +"%m%d")
info=""
ld="${suite}-logs"
gpus=$(nvidia-smi -L | wc -l)
# for x in $(seq 1 1); do
#     shift
# done

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

i=0
INF_MAC_NODE_RANK=0
for e in "${envs[@]}"; do
    config="${config}"
    for a in "${algos[@]}"; do
        for a1 in "${args1[@]}"; do
            for s in {0..4}; do
                kws="n_imaginary_runs=$a1"
                # echo $kws
                env="${suite}-${e}"
                if [[ "$OSTYPE" == 'linux-gnu'* ]]; then
                    gpu=$(($i % $gpus))
                    py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -s $s --gpu $gpu -na $na -kw $kws &"
                else
                    py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -s $s -na $na -kw $kws &"
                fi
                echo $py_script
                eval $py_script
                ((i=(i+1) ))
            done
        done
    done
done
wait
echo "Script completed"