#!/bin/zsh

source activate grl

algos=($1)
suite=grid_world
envs=(staghunt)
config=magw
args1=()
args2=()
args3=(None)
args4=(0)
date=$(date +"%m%d")
date=0817
info=""

for x in $(seq 1 1); do
    shift
done

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

cmdkws=""
for item in $@; do
    if [ -z != $cmdkws ]; then
        cmdkws="$cmdkws-$item"
    else
        cmdkws="$item"
    fi
done


kws="$@"
shift
kw1=""
kwstr="$kw1"
kws="$kws $kw1"
for item in $@; do
    if [ -z != $kwstr ]; then
        kwstr="$kwstr-$item"
    else
        kwstr="$item"
    fi
done

for e in "${envs[@]}"; do
    for a in "${algos[@]}"; do
        for ((s=1; s<=4; s++)); do
            env="${suite}-${e}"
            ld="$suite-logs"
            if [ 0 != $# ]; then
                dir="$ld/$env/$a/$n-$kwstr/seed=$s"
            else
                dir="$ld/$env/$a/$n/seed=$s"
            fi
            mkdir -p $dir
            gpus=$(nvidia-smi -L | wc -l)
            gpu=$((($s-1) % $gpus))
            py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld --gpu $gpu -n $n -s $s $kws -i $info 2> ${dir}/err.txt | tee -a ${dir}/out.txt > /dev/null &"
            echo $py_script
            eval $py_script
            # sleep 3
        done
    done
done
