#!/bin/zsh

# source activate grl

# algos=(
#     $1
# )
# suite=$2
# envs=(
#     $3
# )
# config=$4
# seed=$5
# for x in $(seq 1 5); do
#     shift
# done
# date=$(date +"%m%d")
# info=""

# if [ -z "$info" ]; then
#     n=$date
# else
#     n="$date-$info"
# fi

# cmdkws=""
# for item in $@; do
#     if [ -z != $cmdkws ]; then
#         cmdkws="$cmdkws-$item"
#     else
#         cmdkws="$item"
#     fi
# done


# kws="$@"
# shift
# kw1=""
# kwstr="$kw1"
# kws="$kws $kw1"
# for item in $@; do
#     if [ -z != $kwstr ]; then
#         kwstr="$kwstr-$item"
#     else
#         kwstr="$item"
#     fi
# done

# for e in "${envs[@]}"; do
#     for a in "${algos[@]}"; do
#         for ((s=1; s<=$seed; s++)); do
#             env="${suite}-${e}"
#             ld="$suite-logs"
#             if [ 0 != $# ]; then
#                 dir="$ld/$env/$a/$n-$kwstr/seed=$s"
#             else
#                 dir="$ld/$env/$a/$n/seed=$s"
#             fi
#             mkdir -p $dir
#             gpus=$(nvidia-smi -L | wc -l)
#             gpu=$((($s-1) % $gpus))
#             py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld --gpu $gpu -n $n -s $s $kws -i $info 2> ${dir}/err.txt | tee -a ${dir}/out.txt > /dev/null &"
#             echo $py_script
#             eval $py_script
#             # sleep 3
#         done
#     done
# done

./start_gw zero_ir -kw rl_reward=sum $@
sleep 10s
./start_gw zero_ir -kw rl_reward=meta $@
