#!/bin/zsh

source activate grl

algos=(
    sync-gpo
)
suite=spiel
envs=(
    leduc_poker
)
config=spiel
seeds=(0 1 2)
args1=(pfsp)
args2=(1e-2)
args3=(1 100 1000)
args4=(2)
# date=$(date +"%m%d")
date=0616

shift
i=0
j=1
for e in "${envs[@]}"; do
    for a in "${algos[@]}"; do
        for a1 in "${args1[@]}"; do
            for a2 in "${args2[@]}"; do
                for a3 in "${args3[@]}"; do
                    for a4 in "${args4[@]}"; do
                        for seed in "${seeds[@]}"; do
                            cmdkws=""
                            for item in $@; do
                                if [ -z != $cmdkws ]; then
                                    cmdkws="$cmdkws-$item"
                                else
                                    cmdkws="$item"
                                fi
                            done
                            kw1="sampling_strategy:type=$a1"
                            kw2="step_size=$a2"
                            kw3="update_interval=$a3"
                            kw4="p=$a4"
                            kwstr="$kw1-$kw2-$kw3-$kw4"
                            if [ 0 != $# ]; then
                                kwstr="$cmdkws-$kwstr"
                            fi
                            env="${suite}-${e}"
                            n="$date"
                            ld="logs-$suite"
                            dir="$ld/$env/$a/$n-$kwstr-seed=$seed"
                            mkdir -p $dir
                            if [ "0" = $# ]; then
                                kws="$kw1 $kw2 $kw3 $kw4"
                            else
                                kws="$@ $kw1 $kw2 $kw3 $kw4"
                            fi
                            py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -kw $kws -s $seed -v info 2> ${dir}/err.txt | tee -a ${dir}/out.txt > /dev/null &"
                            echo $py_script
                            eval $py_script
                            sleep 3
                        done
                    done
                done
            done
        done
    done
done

# config=spiel
# seeds=(0)
# args1=(1 100 1000)
# date=$(date +"%m%d")

# for e in "${envs[@]}"; do
#     for a in "${algos[@]}"; do
#         for a1 in "${args1[@]}"; do
#             for seed in "${seeds[@]}"; do
#                 cmdkws=""
#                 for item in $@; do
#                     if [ -z != $cmdkws ]; then
#                         cmdkws="$cmdkws-$item"
#                     else
#                         cmdkws="$item"
#                     fi
#                 done
#                 kw1="update_interval=$a1"
#                 kwstr="$kw1"
#                 if [ 0 != $# ]; then
#                     kwstr="$cmdkws-$kwstr"
#                 fi
#                 env="${suite}-${e}"
#                 n="$date"
#                 ld="logs-$suite"
#                 dir="$ld/$env/$a/$n-$kwstr-seed=$seed"
#                 mkdir -p $dir
#                 if [ "0" = $# ]; then
#                     kws="$kw1"
#                 else
#                     kws="$@ $kw1"
#                 fi
#                 py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -kw $kws -s $seed -v info 2> ${dir}/err.txt | tee -a ${dir}/out.txt > /dev/null &"
#                 echo $py_script
#                 eval $py_script
#                 sleep 3
#             done
#         done
#     done
# done
