#!/bin/zsh

source activate grl

algos=(
    sync-gpo
)
suite=spiel
envs=(
    leduc_poker
)
config=spiel
seeds=(0 1 2)
args1=(pfsp)
args2=($1)
args3=(.1)
args4=(1)
date=$(date +"%m%d")
# date=0626
info="online_frac=.25"
n="$date-$info"
k1="sampling_strategy:type"
k2="max_steps_per_iteration"
k3="step_size"
k4="p"

# shift
# i=0
# j=1
# for e in "${envs[@]}"; do
#     for a in "${algos[@]}"; do
#         for a1 in "${args1[@]}"; do
#             for a2 in "${args2[@]}"; do
#                 for a3 in "${args3[@]}"; do
#                     for a4 in "${args4[@]}"; do
#                         for seed in "${seeds[@]}"; do
#                             cmdkws=""
#                             for item in $@; do
#                                 if [ -z != $cmdkws ]; then
#                                     cmdkws="$cmdkws-$item"
#                                 else
#                                     cmdkws="$item"
#                                 fi
#                             done
#                             kw1="$k1=$a1"
#                             kw2="$k2=$a2"
#                             kw3="$k3=$a3"
#                             kw4="$k4=$a4"
#                             kwstr="$kw1-$kw2-$kw3-$kw4"
#                             if [ 0 != $# ]; then
#                                 kwstr="$cmdkws-$kwstr"
#                             fi
#                             env="${suite}-${e}"
#                             ld="logs-$suite"
#                             dir="$ld/$env/$a/$n-$kwstr/seed=$seed"
#                             mkdir -p $dir
#                             if [ "0" = $# ]; then
#                                 kws="$kw1 $kw2 $kw3 $kw4"
#                             else
#                                 kws="$@ $kw1 $kw2 $kw3 $kw4"
#                             fi
#                             py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -kw $kws -s $seed -v info -i $info 2> ${dir}/err.txt | tee -a ${dir}/out.txt > /dev/null &"
#                             echo $py_script
#                             eval $py_script
#                             sleep 3
#                         done
#                     done
#                 done
#             done
#         done
#     done
# done


for e in "${envs[@]}"; do
    for a in "${algos[@]}"; do
        for seed in "${seeds[@]}"; do
            env="${suite}-${e}"
            ld="logs-$suite"
            dir="$ld/$env/$a/$n/seed=$seed"
            mkdir -p $dir
            py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -s $seed -v info -i $info 2> ${dir}/err.txt | tee -a ${dir}/out.txt > /dev/null &"
            echo $py_script
            eval $py_script
            sleep 3
        done
    done
done

# python run/train.py -a sync-gpo -e spiel-leduc_poker -c spiel -ld logs-spiel -p $1 -s 0 \
#     -kw max_steps_per_iteration=1000 max_version_iterations=1 n_runners=1
