#!/bin/zsh

source activate grl

algos=(zero_mr)
suite=grid_world
envs=(staghunt)
config=magw_a2c
args1=(0)
args2=(1e-2 5e-2 1e-1)
args3=(5e-4 1e-3 3e-3)
args4=(4 8)
date=$(date +"%m%d")
info=""

# for x in $(seq 1 2); do
#     shift
# done

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

cmdkws=""
for item in $@; do
    if [ -z != $cmdkws ]; then
        cmdkws="$cmdkws-$item"
    else
        cmdkws="$item"
    fi
done


i=0
for e in "${envs[@]}"; do
    for a in "${algos[@]}"; do
        for a1 in "${args1[@]}"; do
            for a2 in "${args2[@]}"; do
                for a3 in "${args3[@]}"; do
                    for a4 in "${args4[@]}"; do
                        for ((s=1; s<=4; s++)); do
                            kw1="K=$a1"
                            kw2="entropy_coef=$a2"
                            kw3="rl_opt:lr=$a3"
                            kw4="n_steps=$a4"
                            kwstr="$kw1-$kw2-$kw3-$kw4"
                            kws="$kw1 $kw2 $kw3 $kw4"
                            if [ 0 != $# ]; then
                                kwstr="$cmdkws-$kwstr"
                                kws="$@ $kws"
                            fi
                            env="${suite}-${e}"
                            ld="${suite}-logs"
                            gpus=$(nvidia-smi -L | wc -l)
                            gpu=$(($i % $gpus))
                            dir="$ld/$env/$a/$n-$kwstr/seed=$s"
                            # dir="$ld/$env/$a/$n-seed=$s"
                            mkdir -p $dir
                            # py_script="python run/train.py -a ${a} -e $env -c $config -kw $kw1 $kw2 $kw3 $kw4 -ld $ld --gpu $i -n $n -s $seed | tee ${dir}/outputs.txt &"
                            # py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld --gpu $i -n $n -s $seed | tee ${dir}/outputs.txt &"
                            py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld --gpu $gpu -n $n -s $s -kw $kws -i $info 2> ${dir}/err.txt | tee -a ${dir}/out.txt > /dev/null &"
                            echo $py_script
                            eval $py_script
                            sleep 3
                            ((i=(i+1) ))
                        done
                    done
                done
            done
        done
    done
done

# kws="$@"
# shift
# kw1=""
# kwstr="$kw1"
# kws="$kws $kw1"
# for item in $@; do
#     if [ -z != $kwstr ]; then
#         kwstr="$kwstr-$item"
#     else
#         kwstr="$item"
#     fi
# done

# for e in "${envs[@]}"; do
#     for a in "${algos[@]}"; do
#         for ((s=1; s<=4; s++)); do
#             env="${suite}-${e}"
#             ld="$suite-logs"
#             if [ 0 != $# ]; then
#                 dir="$ld/$env/$a/$n-$kwstr/seed=$s"
#             else
#                 dir="$ld/$env/$a/$n/seed=$s"
#             fi
#             mkdir -p $dir
#             gpus=$(nvidia-smi -L | wc -l)
#             gpu=$((($s-1) % $gpus))
#             py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld --gpu $gpu -v info -n $n -s $s $kws -i $info 2> ${dir}/err.txt | tee -a ${dir}/out.txt > /dev/null &"
#             echo $py_script
#             eval $py_script
#             # sleep 3
#         done
#     done
# done
