#!/bin/zsh

source activate grl

algos=(
    # ppo
    # ppo_meta
    # ppg
    # apex-dqn
    # apex-iqn
    # apex-mrdqn
    # daac
    # apex-mrdqn
    # sacdiqn5
    zero
)
suite=card
envs=(
    # leaper
    # ninja
    # chaser
    # bigfish
    # plunder
    # heist
    # starpilot
    # miner
    # climber
    # dodgeball
    # caveflyer 
    # jumper
    # fruitbot
    # bossfight
    # maze
    # coinrun
    gd2
)
args1=(1 2)
args2=(128 256)
args3=(True)
args4=(True)

# algos=(
#     apg-ppo
# )
# suite=procgen
# envs=(
    
# )

i=4
for e in "${envs[@]}"; do
    for a in "${algos[@]}"; do
        for a1 in "${args1[@]}"; do
            for a2 in "${args2[@]}"; do
                for a3 in "${args3[@]}"; do
                    for a4 in "${args3[@]}"; do
                        # if [[ $a2 == $a3 ]]
                        # then continue
                        # fi
                        # sed -e "s/KI/${a2}/g" \
                        #     algo/ppo/${suite}_template.yaml > algo/ppo/${suite}_config.yaml
                        # dir="logs/${suite}_${e}/${a}"
                        kw1="N_MBS=$a1"
                        kw2="N_STEPS=$a2"
                        kw3="use_ln=$a3"
                        kw4="norm_after_activation=$a4"
                        env="${suite}_${e}"
                        dir="logs/$a/$env/$kw1-$kw2"
                        mkdir -p $dir
                        # py_script="train ${a} -e ${suite}_${e} $@ >& ${dir}/outputs.txt"
                        # py_script="train ${a} -e ${suite}_${e} -kw distribution_mode=hard >& ${dir}/outputs.txt"
                        py_script="CUDA_VISIBLE_DEVICES=$i python run/train.py ${a} -e $env -kw $kw1 $kw2 >& ${dir}/outputs.txt &"
                        echo $py_script
                        eval $py_script
                        ((i=(i+1) % 8))
                        sleep 3
                        # last_dir=$(ls -td ${dir}/* | grep -v txt | head -n 1)
                        # mv_script="mv ${dir}/outputs.txt ${last_dir}/outputs.txt"
                        # echo $mv_script
                        # eval $mv_script
                    done
                done
            done
        done
    done
done
