---
algorithm: &algo async-sac
name: async-sac
info: async-sac

precision: 32

n_agents: 1

# model path: root_dir/model_name/name
# tensorboard path: root_dir/model_name/logs
# the following names are just examples; they will be re-specified in the entry point
root_dir: *algo
model_name: *algo

controller:
  store_period: 5e4
  restart_runners_period: null
  max_version_iterations: 1
  max_steps_per_iteration: &ms 5e6
  initialize_rms: &irms True

parameter_server:
  root_dir: *algo
  model_name: *algo

  train_from_scratch_frac: 1
  online_frac: .2

  payoff:
    step_size: 1e-2   # step size towards the most recent data, 0 or null average payoff over the entire history
    update_interval: 180
    sampling_strategy:
      type: pfsp
      p: 1

  # rule_strategies:
  #   # agent name / config
  #   random:
  #     aid: 1
  #     vid: 1
  #     path: rule/random   # path to the file that defines Strategy
  #     # other configs

ray_config:
  runner:
    num_cpus: 1
  agent:
    num_gpus: 0

monitor: 
  max_steps: *ms

runner:
  n_runners: &nrunners 1
  n_steps: &nsteps 100
  push_every_episode: False

env:
  env_name: &env_name mujoco-Walker2d-v3
  n_envs: &nenvs 20
  max_episode_steps: 1000
  to_multi_agent: True
  timeout_done: &td False

agent: {}

strategy:
  algorithm: *algo
  train_loop: 
    n_epochs: 100

model:
  aid: 0
  gamma: &gamma .99
  polyak: .995
  n_Qs: 2

  policy:
    nn_id: policy
    units_list: [256, 256]
    w_init: orthogonal
    activation: relu
    norm: null
    rnn_type: &prnn null
    rnn_units: 64
    LOG_STD_MIN: -20
    LOG_STD_MAX: 2
    use_feature_norm: False
  Q:
    nn_id: Q
    units_list: [256, 256]
    w_init: orthogonal
    activation: relu
    norm: null
    rnn_type: &vrnn null
    rnn_units: 64
    use_feature_norm: False
  temp:
    nn_id: temp
    type: constant
    value: .2

loss:
  prnn_bptt: 10
  vrnn_bptt: 10

  stats:
    gamma: *gamma
    policy_coef: 1
    q_coef: 1
    temp_coef: 1

trainer:
  algorithm: *algo
  aid: 0

  policy_opt:
    opt_name: adam
    lr: 1e-3
    clip_norm: 10
    eps: 1e-5
  Q_opt:
    opt_name: adam
    lr: 1e-3
    clip_norm: 10
    eps: 1e-5
  temp_opt:
    opt_name: adam
    lr: 1e-3
    clip_norm: 10
    eps: 1e-5

actor: {}

buffer:
  type: uniform

  n_runners: *nrunners
  n_envs: *nenvs
  max_size: 1e6
  min_size: 1e4
  batch_size: 100
  sample_size: 1

  max_steps: 1
  gamma: *gamma

  n_steps: *nsteps
  sample_keys:
    - obs
    - action
    - reward
    - discount
    - steps
