#!/bin/bash

export PYTHONPATH=.

suite=aircombat
algos=(
    ppo
)
envs=(
    '1'
)
# shift
configs=$suite
args1=(
    8e-4
    8e-4
    8e-4
    8e-4
    1e-3
    1e-3
    1e-3
    1e-3
)
args2=(
    15
    15
    20
    20
)
args3=(
    True
    False
)
args4=(
    True
    # False
    # .1
)
date=$(date +"%m%d")
# date=0519
info=""
ld="${suite}-logs"

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

le=${#envs[@]}
idx=$(($NODE_ID % $le))
e=${envs[$idx]}
env="${suite}-${e}"
lc=${#configs[@]}
idx=$(($NODE_ID % $lc))
config=${configs[$idx]}
la=${#algos[@]}
idx=$(($NODE_ID % $la))
a=${algos[$idx]}
la1=${#args1[@]}
idx=$(($NODE_ID % $la1))
a1=${args1[$idx]}
la2=${#args2[@]}
idx=$(($NODE_ID % $la2))
a2=${args2[$idx]}
la3=${#args3[@]}
idx=$(($NODE_ID % $la3))
a3=${args3[$idx]}
# kws=$@

commands=()
kw1=entropy_coef
kw2=lr
kw3=abc
# for e in "${envs[@]}"; do
# for a1 in "${args1[@]}"; do
kws="$kw1=$a1 $kw2=$a2 $kw3=$a3"
env="${suite}-${e}"
config="${suite}"
# i=$(($NODE_ID % 2))
# if [ "$i" -eq 0 ]; then
#     for s in {0..4}; do
#         py_script="python run/train.py -a $a $dynamics -e $env -c $config -ld $ld -n $n -te train_grf -kw $kws -s $s"
#         commands+=("$py_script")
#         echo $py_script
#     done
# else
#     for s in {5..9}; do
#         py_script="python run/train.py -a $a $dynamics -e $env -c $config -ld $ld -n $n -te train_grf -kw $kws -s $s"
#         commands+=("$py_script")
#         echo $py_script
#     done
# fi
for a in "${algos[@]}"; do
  for e in "${envs[@]}"; do
    for s in {0..4}; do
        py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -kw $kws -s $s"
        commands+=("$py_script")
        echo $py_script
    done
  done
done
printf '%s\n' "${commands[@]}" | xargs -I COMMAND -P 5 -L 1 bash -c COMMAND 
echo "Script completed"
