#!/bin/bash

export PYTHONPATH=.

commands=()
envs=(
    escalation
)
for e in "${envs[@]}"; do
    kws=""
    for s in {0..8}; do
        py_script="python run/train.py -a happo -e magw-$e -c escalation -ld magw-logs -kw $kws -s $s"
        commands+=("$py_script")
        echo $py_script
    done
done
for e in "${envs[@]}"; do
    kws="0#rescaled_by_adv=True 0#rescaled_by_mu=False 0#sample_pos_reg_coef=1"
    for s in {0..8}; do
        py_script="python run/train.py -a happo -e magw-$e -c escalation -ld magw-logs -kw $kws -s $s"
        commands+=("$py_script")
        echo $py_script
    done
done
for e in "${envs[@]}"; do
    kws="0#rescaled_by_adv=True 0#rescaled_by_mu=False 0#sample_reg_coef=1"
    for s in {0..8}; do
        py_script="python run/train.py -a happo -e magw-$e -c escalation -ld magw-logs -kw $kws -s $s"
        commands+=("$py_script")
        echo $py_script
    done
done
printf '%s\n' "${commands[@]}" | xargs -I COMMAND -P 16 -L 1 bash -c COMMAND
echo "Script completed"
