#!/bin/bash

export PYTHONPATH=.

commands=()
envs=(
    escalation
)
python run/train.py -a happo -e grf-academy_3_vs_1_with_keeper -c academy_3_vs_1_with_keeper -ld grf-logs -n 0517 -kw -s 2 &
python run/train.py -a happo -e grf-academy_3_vs_1_with_keeper -c academy_3_vs_1_with_keeper -ld grf-logs -n 0518 -kw -s 2 &
wait
echo "Script completed"
