#!/bin/bash

export PYTHONPATH=.

suite=grf
algos=(
    happo_mb
)
envs=(
    # $1
    academy_3_vs_1_with_keeper
    # academy_corner
    # academy_counterattack_hard
    # academy_custom_counterattack_hard
)
# shift
configs=$envs
args1=(
    300
    500
    800
    # 300
    # 800
    # 4096
)
args2=(
    1024
    2048
    # 4096
    # 2048
    # 1e-3
)
args3=(
    1e4
    1e5
)
args4=(
    True
    # False
    # .1
)
date=$(date +"%m%d")
# date="0516"
info=""
ld="${suite}-logs"

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

dynamics=dynamics
commands=()
if [[ "$OSTYPE" == 'linux-gnu'* ]]; then
    i=0
    for a in "${algos[@]}"; do
        for e in "${envs[@]}"; do
            for a2 in "${args2[@]}"; do
                for a1 in "${args1[@]}"; do
                    for a3 in "${args3[@]}"; do
                        kws="1#n_epochs=$a1 1#batch_size=$a2 1#max_size=$a3 debug=True"
                        env="${suite}-${e}"
                        config="${e}"
                        for s in {0..2}; do
                            gpus=$(nvidia-smi -L | wc -l)
                            gpu=$(($i % $gpus))
                            py_script="python run/train.py -a $a $dynamics -e $env -c $config -ld $ld -n $n -te train_grf -kw $kws -s $s --gpu $gpu 2> /dev/null"
                            commands+=("$py_script")
                            echo $py_script
                            # eval $py_script
                            # sleep 3
                            ((i=(i+1) ))
                        done
                    done
                done
            done
        done
    done
    printf "%s\n" "${commands[@]}" | xargs -P 6 -I {} bash -c "{}"
else
    le=${#envs[@]}
    idx=$(($INF_MAC_NODE_RANK % $le))
    e=${envs[$idx]}
    env="${suite}-${e}"
    lc=${#configs[@]}
    idx=$(($INF_MAC_NODE_RANK % $lc))
    config=${configs[$idx]}
    la=${#algos[@]}
    idx=$(($INF_MAC_NODE_RANK % $la))
    a=${algos[$idx]}
    la1=${#args1[@]}
    idx=$(($INF_MAC_NODE_RANK % $la1))
    a1=${args1[$idx]}
    la2=${#args2[@]}
    idx=$(($INF_MAC_NODE_RANK % $la2))
    a2=${args2[$idx]}
    la3=${#args3[@]}
    idx=$(($INF_MAC_NODE_RANK % $la3))
    a3=${args3[$idx]}

    kws="1#n_epochs=$a1 1#batch_size=$a2 1#lr=$a3 1#max_size=5e5 debug=True"
    env="${suite}-${e}"
    config="${e}"
    # kws=$@
    for s in {0..0}; do
        py_script="python run/train.py -a $a $dynamics -e $env -c $config -ld $ld -n $n -te train_grf -kw $kws -s $s"
        commands+=("$py_script")
        echo $py_script
    done
    printf '%s\n' "${commands[@]}" | xargs -I COMMAND -P 6 -L 1 bash -c COMMAND 
fi

# kws=$@
# dynamics=$1
# e=$1
# shift
# for e in "${envs[@]}"; do

echo "Script completed"
