#!/bin/bash

export PYTHONPATH=.

suite=grf
algos=(
    happo_mb
)
envs=(
    # $1
    academy_3_vs_1_with_keeper
    academy_corner
    academy_counterattack_hard
    # academy_custom_counterattack_hard
)
# shift
configs=$envs
args1=(
    10
)
args2=(
    # $1
    1000
    2000
    # 4096
    # 2048
    # 1e-3
)
args3=(
    # $2
    15
    10
)
args4=(
    # $3
    1
    5
)
date=$(date +"%m%d")
info=""
ld="${suite}-logs"

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

dynamics=dynamics
commands=()
if [[ "$OSTYPE" == 'linux-gnu'* ]]; then
    i=0
    for a in "${algos[@]}"; do
        for e in "${envs[@]}"; do
            for a2 in "${args2[@]}"; do
                for a1 in "${args1[@]}"; do
                    for a3 in "${args3[@]}"; do
                        for a4 in "${args4[@]}"; do
                            kws="compute_return_at_once=True target_type=gae 0#n_lka_epochs=$a1 0#n_simulated_envs=$a2 0#n_simulated_steps=$a3 1#n_epochs=1500 1#reward_coef=$a4 debug=True"
                            env="${suite}-${e}"
                            config="${e}"
                            for s in {0..4}; do
                                gpus=$(nvidia-smi -L | wc -l)
                                gpu=$(($i % $gpus))
                                py_script="python run/train.py -a $a $dynamics -e $env -c $config -ld $ld -n $n -te train_grf -kw $kws -s $s --gpu $gpu"
                                commands+=("$py_script")
                                echo $py_script
                                # eval $py_script
                                # sleep 3
                                ((i=(i+1) ))
                            done
                        done
                    done
                done
            done
        done
    done
    printf "%s\n" "${commands[@]}" | xargs -s 1024 -P 10 -I {} bash -c "{}"
else
    le=${#envs[@]}
    idx=$(($INF_MAC_NODE_RANK % $le))
    e=${envs[$idx]}
    env="${suite}-${e}"
    lc=${#configs[@]}
    idx=$(($INF_MAC_NODE_RANK % $lc))
    config=${configs[$idx]}
    la=${#algos[@]}
    idx=$(($INF_MAC_NODE_RANK % $la))
    a=${algos[$idx]}
    la1=${#args1[@]}
    idx=$(($INF_MAC_NODE_RANK % $la1))
    a1=${args1[$idx]}
    la2=${#args2[@]}
    idx=$(($INF_MAC_NODE_RANK % $la2))
    a2=${args2[$idx]}
    la3=${#args3[@]}
    idx=$(($INF_MAC_NODE_RANK % $la3))
    a3=${args3[$idx]}
    la4=${#args4[@]}
    idx=$(($INF_MAC_NODE_RANK % $la4))
    a4=${args4[$idx]}

    # kws=""
    env="${suite}-${e}"
    config="${e}"
    kws=$@
    for s in {0..4}; do
        py_script="python run/train.py -a $a $dynamics -e $env -c $config -ld $ld -n $n -te train_grf -kw $kws -s $s"
        commands+=("$py_script")
        echo $py_script
    done
    printf '%s\n' "${commands[@]}" | xargs -S 1024 -I COMMAND -P 5 -L 1 bash -c COMMAND
fi

# kws=$@
# dynamics=$1
# e=$1
# shift
# for e in "${envs[@]}"; do

echo "Script completed"
