#!/bin/bash

export PYTHONPATH=.

suite=$1
shift
algos=(
    happo_mb
)
envs=(
    $1
    Ant_2x4
    HalfCheetah_2x3
    Walker2d_2x3
)
shift
configs=(
    "${suite}"
)
args1=(
    $1
    50
    100
)
args2=(
    # $2
    400
    800
)
args3=(
    $3
    1
)
dynamics=(
    "dynamics"
)
date=$(date +"%m%d")
# date="0403"
info=""
ld="${suite}-logs"
gpus=$(nvidia-smi -L | wc -l)

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

# INF_MAC_NODE_RANK=$1
le=${#envs[@]}
idx=$(($INF_MAC_NODE_RANK % $le))
e=${envs[$idx]}
env="${suite}-${e}"
lc=${#configs[@]}
idx=$(($INF_MAC_NODE_RANK % $lc))
config=${configs[$idx]}
la=${#algos[@]}
idx=$(($INF_MAC_NODE_RANK % $la))
a=${algos[$idx]}
ldy=${#dynamics[@]}
idx=$(($INF_MAC_NODE_RANK % $ldy))
d=${dynamics[$idx]}
la1=${#args1[@]}
idx=$(($INF_MAC_NODE_RANK % $la1))
a1=${args1[$idx]}
la2=${#args2[@]}
idx=$(($INF_MAC_NODE_RANK % $la2))
a2=${args2[$idx]}
la3=${#args3[@]}
idx=$(($INF_MAC_NODE_RANK % $la3))
a3=${args3[$idx]}

commands=()
# for a1 in "${args1[@]}"; do
# for a2 in "${args2[@]}"; do
kws="1#n_epochs=$a1"
env="${suite}-${e}"
for s in {0..9}; do
    py_script="python run/train.py -a ${a} $d -e $env -c $config -ld $ld -n $n -kw $kws -s $s"
    commands+=("$py_script")
    echo $py_script
done
# done
# done
# a="happo_lka2"
# kws="1#n_epochs=$a1"
# env="${suite}-${e}"
# for s in {0..7}; do
#     py_script="python run/train.py -a ${a} $d -e $env -c $config -ld $ld -n $n -kw $kws -s $s"
#     commands+=("$py_script")
#     echo $py_script
# done
printf '%s\n' "${commands[@]}" | xargs -I COMMAND -P 16 -L 1 bash -c COMMAND
echo "Script completed"
