#!/bin/bash

export PYTHONPATH=.

suite=$1
shift
envs=(
    escalation
    staghunt
)
algos=(
    # $1
    happo
    happo
    # happo
    # happo_lka1
    # happo_lka1
    happo_lka2
    happo_lka2
)
args1=(
    # ppo
    # correct_ppo
    # 10
    1
    .1
    # 10
    # 20
    # 20
    # 20
    # 30
    # 30
    # 15
    # 20
    # 20
)
args2=(
    # $3
    256
    400
)
args3=(
    10
)
# date=$(date +"%m%d")
date="0330"
info=""
ld="${suite}-logs"
# gpus=$(nvidia-smi -L | wc -l)
# for x in $(seq 1 1); do
#     shift
# done

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

le=${#envs[@]}
idx=$(($INF_MAC_NODE_RANK % $le))
e=${envs[$idx]}
env="${suite}-${e}"
# lc=${#configs[@]}
# idx=$(($INF_MAC_NODE_RANK % $lc))
# config=${configs[$idx]}
la=${#algos[@]}
idx=$(($INF_MAC_NODE_RANK % $la))
a=${algos[$idx]}
la1=${#args1[@]}
idx=$(($INF_MAC_NODE_RANK % $la1))
a1=${args1[$idx]}
la2=${#args2[@]}
idx=$(($INF_MAC_NODE_RANK % $la2))
a2=${args2[$idx]}
la3=${#args3[@]}
idx=$(($INF_MAC_NODE_RANK % $la3))
a3=${args3[$idx]}
# kws=$@

commands=()
for a2 in "${args2[@]}"; do
    kws="0#norm_adv=False 0#n_envs=$a2 0#pos_kl_coef=$a1"
    for e in "${envs[@]}"; do
        config=$e
        env="${suite}-${e}"
        for s in {0..7}; do
            py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -kw $kws -s $s"
            commands+=("$py_script")
            echo $py_script
        done
    done
done
for a2 in "${args2[@]}"; do
    kws="0#norm_adv=False 0#n_envs=$a2 0#pos_kl_coef=$a1"
    for e in "${envs[@]}"; do
        config=$e
        env="${suite}-${e}"
        for s in {8..15}; do
            py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -kw $kws -s $s"
            commands+=("$py_script")
            echo $py_script
        done
    done
done
# config=$e
# kws="0#norm_adv=False 0#pos_kl_coef=$a1"
# for e in "${envs[@]}"; do
#     env="${suite}-${e}"
#     for s in {0..7}; do
#         py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -kw $kws -s $s"
#         commands+=("$py_script")
#         echo $py_script
#     done
# done
# echo ${commands[@]}s
printf '%s\n' "${commands[@]}" | xargs -I COMMAND -P 16 -L 1 bash -c COMMAND 
echo "Script completed"
