#!/bin/bash

export PYTHONPATH=.

suite=$1
shift
algos=(
    mambpo
    # mambpo
    # mambpo_lka2
    mambpo_lka2
)
envs=(
    # Ant_2x4
    HalfCheetah_2x3
    Walker2d_2x3
)
configs=(
    "${suite}"
)
args1=(
    # $1
    # 200
    400
    800
    # 1000
)
args2=(
    # $2
    .1
    .3
    .5
)
args3=(
    300
    500
    # 800
)
args4=(
    200
    400
)
dynamics=(
    # "dynamics_tx"
    # "dynamics_tx"
    # "dynamics_tx"
    "dynamics"
    # "dynamics2"
)
date=$(date +"%m%d")
info=""
ld="${suite}-logs"
gpus=$(nvidia-smi -L | wc -l)
# for x in $(seq 1 1); do
#     shift
# done

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

# INF_MAC_NODE_RANK=$1
le=${#envs[@]}
idx=$(($INF_MAC_NODE_RANK % $le))
e=${envs[$idx]}
env="${suite}-${e}"
lc=${#configs[@]}
idx=$(($INF_MAC_NODE_RANK % $lc))
config=${configs[$idx]}
la=${#algos[@]}
idx=$(($INF_MAC_NODE_RANK % $la))
a=${algos[$idx]}
ldy=${#dynamics[@]}
idx=$(($INF_MAC_NODE_RANK % $ldy))
d=${dynamics[$idx]}
la1=${#args1[@]}
idx=$(($INF_MAC_NODE_RANK % $la1))
a1=${args1[$idx]}
la2=${#args2[@]}
idx=$(($INF_MAC_NODE_RANK % $la2))
a2=${args2[$idx]}
la3=${#args3[@]}
idx=$(($INF_MAC_NODE_RANK % $la3))
a3=${args3[$idx]}

commands=()
# for a4 in "${args4[@]}"; do
kws=$@
kws="0#n_epochs=$a1 0#primal_percentage=$a2 1#n_epochs=$a3"
for e in "${envs[@]}"; do
    config=${suite}
    dyna_config="${suite}_mbpo"
    env="${suite}-${e}"
    for s in {0..3}; do
        py_script="python run/train.py -a ${a} $d -e $env -c $config $dyna_config -ld $ld -n $n -s $s -kw $kws"
        commands+=("$py_script")
        echo $py_script
        # eval $py_script
    done
done
# echo ${commands[@]}s
# lc=${#commands[@]}
# p=$((lc / le))
# echo $p
printf '%s\n' "${commands[@]}" | xargs -I COMMAND -P 16 -L 1 bash -c COMMAND
echo "Script completed"
