#!/bin/bash

export PYTHONPATH=.

suite=$1
shift
envs=(
    escalation
    staghunt
)
algos=(
    # $1
    happo
    # happo
    # happo_lka1
    # happo_lka1
    # happo_lka2
    happo_lka2
)
args1=(
    ppo
)
args2=(
    $3
    64
    128
    256
)
args3=(10)
date=$(date +"%m%d")
# date="0204"
info=""
ld="${suite}-logs"
# gpus=$(nvidia-smi -L | wc -l)
# for x in $(seq 1 1); do
#     shift
# done

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

le=${#envs[@]}
idx=$(($INF_MAC_NODE_RANK % $le))
e=${envs[$idx]}
env="${suite}-${e}"
# lc=${#configs[@]}
# idx=$(($INF_MAC_NODE_RANK % $lc))
# config=${configs[$idx]}
la=${#algos[@]}
idx=$(($INF_MAC_NODE_RANK % $la))
a=${algos[$idx]}
la1=${#args1[@]}
idx=$(($INF_MAC_NODE_RANK % $la1))
a1=${args1[$idx]}
la2=${#args2[@]}
idx=$(($INF_MAC_NODE_RANK % $la2))
a2=${args2[$idx]}
la3=${#args3[@]}
idx=$(($INF_MAC_NODE_RANK % $la3))
a3=${args3[$idx]}
# kws=$@

commands=()
for a1 in "${args1[@]}"; do
    kws="0#norm_adv=False"
    for e in "${envs[@]}"; do
        config=$e
        env="${suite}-${e}"
        for s in {0..7}; do
            py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -kw $kws -s $s"
            commands+=("$py_script")
            echo $py_script
        done
    done
done
for a1 in "${args1[@]}"; do
    kws="0#norm_adv=False"
    for e in "${envs[@]}"; do
        config=$e
        env="${suite}-${e}"
        for s in {8..15}; do
            py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -kw $kws -s $s"
            commands+=("$py_script")
            echo $py_script
        done
    done
done
# config=$e
# env="${suite}-${e}"
# for s in {0..15}; do
#     py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -kw $kws -s $s"
#     commands+=("$py_script")
#     echo $py_script
# done
# echo ${commands[@]}s
printf '%s\n' "${commands[@]}" | xargs -I COMMAND -P 16 -L 1 bash -c COMMAND 
echo "Script completed"
