#!/bin/bash


source activate inf

algo=sync-bmg
suite=spiel
env=leduc_poker

config=spiel
args1=(0)
args2=(0)
args3=(1e-4 3e-4 1e-3)
date=$(date +"%m%d")
seed=3
info=""



if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi


kws="$@"
for item in $@; do
    if [ -z != $kwstr ]; then
        kwstr="$kwstr-$item"
    else
        kwstr="$item"
    fi
done


ld="$suite-logs"
env="${suite}-${env}"
if [ 0 != $# ]; then
    root="$ld/$env/$algo/$n-$kwstr"
else
    root="$ld/$env/$algo/$n"
fi


for ((s=1; s<=$seed; s++)); do
    py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -kw $kws -s $s"
    commands+=("$py_script")
    echo $py_script
done

# python run/train.py -a sync-gpo -e spiel-leduc_poker -c spiel -ld logs-spiel -p $1 -s 0 \
#     -kw max_steps_per_iteration=1000 max_version_iterations=1 n_runners=1
