#!/bin/bash

export PYTHONPATH=.

suite=grf
algos=(
  # ppo
  # ppo
  # ppo
  # ppo
  # ppo
  # sync-ppo
  happo
  # happo
  # happo
  # happo
  # happo
  # happo
)
envs=(
  $1
  # 11_vs_11_easy_stochastic
)
shift
configs=(
  # grf_11vs11_ppo
  "grf_11vs11"
)
# shift
args1=(
  1e-3
  1e-3
  3e-4
  3e-4
  5e-4
  5e-4
  # 1e-3
  # 3e-3
  # 5e-3
)
args2=(
  True
  False
)
args3=(
  True
  False
)
args4=(
  True
  # False
  # .1
)
date=$(date +"%m%d")
# date=0519
info=""
ld="${suite}-logs"

if [ -z "$info" ]; then
  n=$date
else
  n="$date-$info"
fi

le=${#envs[@]}
idx=$(($INF_MAC_NODE_RANK % $le))
e=${envs[$idx]}
env="${suite}-${e}"
lc=${#configs[@]}
idx=$(($INF_MAC_NODE_RANK % $lc))
config=${configs[$idx]}
la=${#algos[@]}
idx=$(($INF_MAC_NODE_RANK % $la))
a=${algos[$idx]}
la1=${#args1[@]}
idx=$(($INF_MAC_NODE_RANK % $la1))
a1=${args1[$idx]}
la2=${#args2[@]}
idx=$(($INF_MAC_NODE_RANK % $la2))
a2=${args2[$idx]}
la3=${#args3[@]}
idx=$(($INF_MAC_NODE_RANK % $la3))
a3=${args3[$idx]}
# kws=$@

commands=()
kws=$@
# for e in "${envs[@]}"; do
# for a1 in "${args1[@]}"; do
# kws="$@ entropy_coef=$a1"
# i=$(($INF_MAC_NODE_RANK % 2))
# if [ "$i" -eq 0 ]; then
#   for s in {0..4}; do
#     py_script="python run/train.py -a $a $dynamics -e $env -c $config -ld $ld -n $n -te train_grf -kw $kws -s $s"
#     commands+=("$py_script")
#     echo $py_script
#   done
# else
#   for s in {5..9}; do
#     py_script="python run/train.py -a $a $dynamics -e $env -c $config -ld $ld -n $n -te train_grf -kw $kws -s $s"
#     commands+=("$py_script")
#     echo $py_script
#   done
# fi
kws="n_epochs=$1 n_mbs=$2 lr=$3 entropy_coef=$4"
# for a in "${algos[@]}"; do
for e in "${envs[@]}"; do
  env="${suite}-${e}"
  for s in {0..2}; do
    py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -kw $kws -s $s"
    commands+=("$py_script")
    echo $py_script
  done
done
# done
printf '%s\n' "${commands[@]}" | xargs -I COMMAND -P 5 -L 1 bash -c COMMAND 
echo "Script completed"
