#!/bin/bash

export PYTHONPATH=.

suite=$1
shift
algos=(
    happo
    # happo_lka1
    happo_lka2
    # $1
    # masac_lka1
    # mambpo
)
envs=(
    Ant_2x4
    Walker2d_2x3
    HalfCheetah_2x3
)
configs=(
    "${suite}"
)
args1=(
    ppo
)
args2=(
    $2
    1
)
args3=(
    $3
    1
)
date=$(date +"%m%d")
info=""
ld="${suite}-logs"
gpus=$(nvidia-smi -L | wc -l)
# for x in $(seq 1 1); do
#     shift
# done

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

# INF_MAC_NODE_RANK=$1
le=${#envs[@]}
idx=$(($INF_MAC_NODE_RANK % $le))
e=${envs[$idx]}
env="${suite}-${e}"
lc=${#configs[@]}
idx=$(($INF_MAC_NODE_RANK % $lc))
config=${configs[$idx]}
la=${#algos[@]}
idx=$(($INF_MAC_NODE_RANK % $la))
a=${algos[$idx]}
la1=${#args1[@]}
idx=$(($INF_MAC_NODE_RANK % $la1))
a1=${args1[$idx]}
la2=${#args2[@]}
idx=$(($INF_MAC_NODE_RANK % $la2))
a2=${args2[$idx]}
la3=${#args3[@]}
idx=$(($INF_MAC_NODE_RANK % $la3))
a3=${args3[$idx]}

commands=()
# kws="update_scheme=$a1"
for a1 in "${args1[@]}"; do
    for a in "${algos[@]}"; do
        kws="0#norm_adv=False"
        for e in "${envs[@]}"; do
            env="${suite}-${e}"
            for s in {0..3}; do
                py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -kw $kws -s $s"
                commands+=("$py_script")
                echo $py_script
                # eval $py_script
            done
        done
    done
done
# echo ${commands[@]}s
lc=${#commands[@]}
p=$((lc / le))
# echo $p
printf '%s\n' "${commands[@]}" | xargs -I COMMAND -P 16 -L 1 bash -c COMMAND
echo "Script completed"
