#!/bin/bash

# brew install ffmpeg
export PYTHONPATH=.

algos=(zero zero_oc)
suite=magw
envs=(
    staghunt
    escalation
)
args1=(50 100)
args2=(8e-4 1e-3)
args3=(.01 .1)
date=$(date +"%m%d")
info=""
ld="${suite}-logs"

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

for e in "${envs[@]}"; do
    config=$e
    for a in "${algos[@]}"; do
        for s in {1..5}; do
            env="${suite}-${e}"
            py_script="python run/train.py -a ${a} ${a} -e $env -c $config -ld $ld -n $n -s $s -kw $kws -ki 0 1 &"
            echo $py_script
            eval $py_script
        done
    done
done
for e in "${envs[@]}"; do
    config=$e
    for s in {1..5}; do
        env="${suite}-${e}"
        a=zero_mb
        py_script="python run/train.py -a ${a} ${a} magw -e $env -c $config -ld $ld -n $n -s $s -kw $kws -ki 0 1 &"
        echo $py_script
        eval $py_script
    done
done

wait
echo "Script completed"
