#!/bin/bash
export PYTHONPATH=.

algos=(zero_mb)
suite=magw
envs=(escalation)
args1=(256 512)
args2=(10 20 30)
args3=(False)
date=$(date +"%m%d")
info=""
ld="${suite}-logs"
# for x in $(seq 1 3); do
#     shift
# done

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

INF_MAC_NODE_RANK=0
for e in "${envs[@]}"; do
    config=$e
    for a in "${algos[@]}"; do
        # for a2 in "${args2[@]}"; do
        for a3 in "${args3[@]}"; do
            for s in {0..0}; do
                la1=${#args1[@]}
                idx=$(($INF_MAC_NODE_RANK % $la1))
                a1=${args1[$idx]}
                la2=${#args2[@]}
                idx=$(($INF_MAC_NODE_RANK % $la2))
                a2=${args2[$idx]}
                kws="n_imaginary_envs=$a1 n_imaginary_steps=$a2 restore_state=$a3"
                env="${suite}-${e}"
                if [[ "$OSTYPE" == 'linux-gnu'* ]]; then
                    gpu=$(($i % $gpus))
                    py_script="python run/train.py -a ${a} ${a} magw -e $env -c $config -ld $ld -n $n -s $s --gpu $gpu -kw $kws &"
                else
                    py_script="python run/train.py -a ${a} ${a} magw -e $env -c $config -ld $ld -n $n -s $s -kw $kws &"
                fi
                echo $py_script
                eval $py_script
                ((i=(i+1) ))
            done
            # done
        done
    done
    # wait
done
wait
echo "Script completed"
# INF_MAC_NODE_RANK=1
# for e in "${envs[@]}"; do
#     for a in "${algos[@]}"; do
#         for a1 in "${args1[@]}"; do
#             for a2 in "${args2[@]}"; do
#                 for a3 in "${args3[@]}"; do
#                     for s in {1..5}; do
#                         # la1=${#args1[@]}
#                         # idx=$(($INF_MAC_NODE_RANK % $la1))
#                         # a1=${args1[$idx]}
#                         # la2=${#args2[@]}
#                         # idx=$(($INF_MAC_NODE_RANK % $la2))
#                         # a2=${args2[$idx]}
#                         kws="n_imaginary_runs=$a1 n_imaginary_envs=$a2"
#                         env="${suite}-${e}"
#                         if [[ "$OSTYPE" == 'linux-gnu'* ]]; then
#                             gpu=$(($i % $gpus))
#                             py_script="python run/train.py -a ${a} ${a} magw -e $env -c $config -ld $ld -n $n -s $s --gpu $gpu -kw $kws -na 3 &"
#                         else
#                             py_script="python run/train.py -a ${a} ${a} magw -e $env -c $config -ld $ld -n $n -s $s -kw $kws -ki 0 1 &"
#                         fi
#                         echo $py_script
#                         # eval $py_script
#                         ((i=(i+1) ))
#                     done
#                 done
#             done
#         done
#     done
# done
# wait
# echo "Script completed"
