#!/bin/bash

export PYTHONPATH=.

algos=(
    happo
    # happo_mb
)
suite=$1
envs=(
    # Ant_8x1
    # HalfCheetah_6x1
    # Walker2d_6x1
    # Ant_4x2
    # HalfCheetah_3x2
    # Walker2d_3x2
    Ant_2x4
    HalfCheetah_2x3
    Walker2d_2x3
)
# e=${suite}
configs=(
    "${suite}"
)
# configs=$envs
args1=(
    dynamics
)
args2=(
    True
    True
    False
    False
)
args3=(
    True
    False
)
date=$(date +"%m%d")
# date="0204"
info=""
ld="${suite}-logs"
# gpus=$(nvidia-smi -L | wc -l)
# for x in $(seq 1 1); do
#     shift
# done

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

le=${#envs[@]}
idx=$(($INF_MAC_NODE_RANK % $le))
e=${envs[$idx]}
env="${suite}-${e}"
lc=${#configs[@]}
idx=$(($INF_MAC_NODE_RANK % $lc))
config=${configs[$idx]}
la=${#algos[@]}
idx=$(($INF_MAC_NODE_RANK % $la))
a=${algos[$idx]}
la1=${#args1[@]}
idx=$(($INF_MAC_NODE_RANK % $la1))
a1=${args1[$idx]}
la2=${#args2[@]}
idx=$(($INF_MAC_NODE_RANK % $la2))
a2=${args2[$idx]}
la3=${#args3[@]}
idx=$(($INF_MAC_NODE_RANK % $la3))
a3=${args3[$idx]}
# kws=$@

commands=()
# kws="trainer:n_epochs=$a1 stoch_trans=$a2 model_loss_type=$a3"
kws="0#dynamics_name=$a1 1#obs_normalization=$a2 1#balance_dimension=$a3"
for e in "${envs[@]}"; do
    env="${suite}-${e}"
    for s in {0..4}; do
        # py_script="python run/train.py -a ${a} dynamics -e $env -c $config -ld $ld -n $n -s $s -kw $kws -ki 2"
        py_script="python run/train.py -a ${a} dynamics -e $env -c $config -ld $ld -n $n -kw $kws -s $s"
        commands+=("$py_script")
        echo $py_script
        # eval $py_script
    done
done
# echo ${commands[@]}s
lc=${#commands[@]}
p=$((lc / le))
printf '%s\n' "${commands[@]}" | xargs -I COMMAND -P 16 -L 1 bash -c COMMAND 
echo "Script completed"
