#!/bin/bash

export PYTHONPATH=.

# python run/mv_dir.py /System/Volumes/Data/mnt/公共区/cxw/grf-logs/grf-academy_3_vs_1_with_keeper/happo_lka/0413 -p a0 dynamics -nd 0412 -mr 1#=
# python run/mv_dir.py /System/Volumes/Data/mnt/公共区/cxw/grf-logs/grf-academy_3_vs_1_with_keeper/happo_lka/0413 -p a0 dynamics -nd 0412 -mr 1#=
python run/mv_dir.py -cp /System/Volumes/Data/mnt/公共区/cxw/magw-logs -nr magw-logs
