#!/bin/bash

# grf
# ./scripts/inf grf 1 inf_grf academy_corner 5 4 200
# ./scripts/inf grf 1 inf_grf academy_3_vs_1_with_keeper 5 4 200
# ./scripts/inf grf 1 inf_grf academy_pass_and_shoot_with_keeper 5 4 200
# ./scripts/inf grf 1 inf_grf academy_run_pass_and_shoot_with_keeper 5 4 200
# ./scripts/inf grf 1 inf_grf academy_counterattack_hard 5 4 200
# ./scripts/inf grf 1 inf_grf academy_counterattack_hard 5 4 1000

./scripts/inf smac 1 inf_smac
