#!/bin/bash

# rsync -a --exclude algo3 \
#     --exclude papers.py --exclude plot.ipynb \
#     --exclude tftest --exclude pg --exclude rename \
#     --exclude sync --exclude __pycache__ \
#     --exclude .gitignore --exclude .git --exclude .vscode \
#     --exclude .ipynb_checkpoints --exclude .pytest_cache \
#     --exclude logs --exclude plots --exclude pytest \
#     --exclude cfr.py --exclude test.py . ~/github/g2rl

rsync -e 'ssh -p 46797' -avz ubuntu@36.111.128.2:/home/ubuntu/chenxinwei/grl/grf-logs/grf-academy_corner/happo_mb/0529 ~/work/Polixir/nas/grf-logs/grf-academy_corner/happo_mb --exclude src
