#!/bin/zsh

source activate inf
conda activate inf

suite=$1
shift
ld="${suite}-logs"
echo $ld

n_nodes=$1 # 申请的mac机子个数
shift
script=$1 # 每台mac上执行的脚本
shift

cmd="sh ./scripts/inf_mac/$script $@"
echo $cmd

if [ $# -eq 0 ]; then
  date=$(date +"%m%d")
  str="$date-$script"
else
  IFS='_'
  date=$(date +"%m%d")
  str="$*"
  str="$date-$script-$str"
fi

inf_mac job run python --exec-command "$cmd" \
  --working-dir . --num-nodes $n_nodes --user chenxw --use-env chenxw \
  --sync-dir ./$ld:/System/Volumes/Data/mnt/公共区/cxw \
  --name $str
