#!/bin/bash

export PYTHONPATH=.

suite=smac
algos=(
  ppo
)
envs=(
  # academy_counterattack_hard
  MMM2
)
# shift
configs=(
  "grf"
)
# shift
args1=(
  True
  False
)
args2=(
  None
  None
  layer
  layer
)
args3=(
  1
)
args4=(
  .2
)
date=$(date +"%m%d")
info=""
ld="${suite}-logs"

if [ -z "$info" ]; then
  n=$date
else
  n="$date-$info"
fi

le=${#envs[@]}
idx=$(($INF_MAC_NODE_RANK % $le))
e=${envs[$idx]}
env="${suite}-${e}"
lc=${#configs[@]}
idx=$(($INF_MAC_NODE_RANK % $lc))
config=${configs[$idx]}
la=${#algos[@]}
idx=$(($INF_MAC_NODE_RANK % $la))
a=${algos[$idx]}
la1=${#args1[@]}
idx=$(($INF_MAC_NODE_RANK % $la1))
a1=${args1[$idx]}
la2=${#args2[@]}
idx=$(($INF_MAC_NODE_RANK % $la2))
a2=${args2[$idx]}
la3=${#args3[@]}
idx=$(($INF_MAC_NODE_RANK % $la3))
a3=${args3[$idx]}
la4=${#args4[@]}
idx=$(($INF_MAC_NODE_RANK % $la4))
a4=${args4[$idx]}
kws=$@

commands=()
kws=$@
# for e in "${envs[@]}"; do
# for a1 in "${args1[@]}"; do
# kws="$@ entropy_coef=$a1"
# i=$(($INF_MAC_NODE_RANK % 2))
# if [ "$i" -eq 0 ]; then
#   for s in {0..4}; do
#     py_script="python run/train.py -a $a $dynamics -e $env -c $config -ld $ld -n $n -te train_grf -kw $kws -s $s"
#     commands+=("$py_script")
#     echo $py_script
#   done
# else
#   for s in {5..9}; do
#     py_script="python run/train.py -a $a $dynamics -e $env -c $config -ld $ld -n $n -te train_grf -kw $kws -s $s"
#     commands+=("$py_script")
#     echo $py_script
#   done
# fi
# for a1 in "${args1[@]}"; do
#   for a2 in "${args2[@]}"; do
for e in "${envs[@]}"; do
  env="${suite}-${e}"
  kws="norm_after_activation=$a1 rnn_norm=$a2"
  for s in {0..2}; do
    py_script="python run/train.py -a ${a} -e $env -c $config -ld $ld -n $n -kw $kws -s $s"
    commands+=("$py_script")
    echo $py_script
  done
done
#   done
# done
printf '%s\n' "${commands[@]}" | xargs -I COMMAND -P 5 -L 1 bash -c COMMAND 
echo "Script completed"
