#!/bin/bash

# brew install ffmpeg
export PYTHONPATH=.

algos=(dynamics)
suite=magw
envs=(staghunt)
config=staghunt
args1=($1)
args2=($2)
shift
shift
args3=(1e-3 5e-4 1e-4)
date=$(date +"%m%d")
info=""
ld="${suite}-logs"
# for x in $(seq 1 1); do
#     shift
# done

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

for s in {0..5}; do
    kws="n_runners=50 runner:num_cpus=1"
    py_script="python run/train.py -a ${a} -e $env -c ${config} -ld $ld -n $nn -s $s -na $na -kw $kws &"
    echo $py_script
    eval $py_script
done

wait
echo "Script completed"
