#!/bin/bash

export PYTHONPATH=.

suite=$1
shift
algos=(
    # $1
    # mambpo
    mambpo_lka2
)
# shift
envs=(
    Ant_2x4
    HalfCheetah_2x3
    Walker2d_2x3
)
configs=(
    "${suite}"
)
args1=(
    $1
    200
)
args2=(
    $2
    True
    True
    False
    False
)
args3=(
    $3
    10
    None
)
args4=(
    # $4
    True
    False
)
dynamics=(
    # $4
    "dynamics"
)
date=$(date +"%m%d")
info=""
ld="${suite}-logs"
gpus=$(nvidia-smi -L | wc -l)
# for x in $(seq 1 1); do
#     shift
# done

if [ -z "$info" ]; then
    n=$date
else
    n="$date-$info"
fi

# INF_MAC_NODE_RANK=$1
le=${#envs[@]}
idx=$(($INF_MAC_NODE_RANK % $le))
e=${envs[$idx]}
env="${suite}-${e}"
lc=${#configs[@]}
idx=$(($INF_MAC_NODE_RANK % $lc))
config=${configs[$idx]}
la=${#algos[@]}
idx=$(($INF_MAC_NODE_RANK % $la))
a=${algos[$idx]}
ldy=${#dynamics[@]}
idx=$(($INF_MAC_NODE_RANK % $ldy))
d=${dynamics[$idx]}
la1=${#args1[@]}
idx=$(($INF_MAC_NODE_RANK % $la1))
a1=${args1[$idx]}
la2=${#args2[@]}
idx=$(($INF_MAC_NODE_RANK % $la2))
a2=${args2[$idx]}
la3=${#args3[@]}
idx=$(($INF_MAC_NODE_RANK % $la3))
a3=${args3[$idx]}

commands=()
# for a4 in "${args4[@]}"; do
#     kws="0#n_epochs=$a1"
kws=$@
for e in "${envs[@]}"; do
    config="${suite}"
    dyna_config="${suite}_mbpo"
    env="${suite}-${e}"
    for s in {0..4}; do
        py_script="python run/train.py -a ${a} $d -e $env -c $config $dyna_config -ld $ld -n $n -kw $kws -s $s"
        commands+=("$py_script")
        echo $py_script
        # eval $py_script
    done
done
printf '%s\n' "${commands[@]}" | xargs -I COMMAND -P 16 -L 1 bash -c COMMAND
echo "Script completed"
